---
title: "The proportion of flatfish recruitment in the North Sea potentially affected by offshore windfarms"
type: "article"
author: "Barbut et al."
year: "2020"
publication: "ICES Journal of Marine Science"
preprint: ""
doi: "https://doi.org/10.1093/icesjms/fsz050"
materials: ""
toc: false
categories:
  - larval transport
  - modeling
  - COHERENS
  - flatfish
  - North Sea
---

## Citation

> **Barbut L.**, Vastenhoud B., Vigin L., Degrear S., Volckaert F.A.M., **Lacroix G.** (2020) The proportion of flatfish recruitment in the North Sea potentially affected by offshore windfarms. ICES Journal of Marine Science, 77(3): 1277-1237.

## Abstract

Understanding the influence of man-made infrastructures on fish population dynamics is an important issue for fisheries management. This is particularly the case because of the steady proliferation of offshore wind farms (OWFs). Several flatfish species are likely to be affected because areas with OWFs in place or planned for show a spatial overlap with their spawning grounds. This study focuses on six commercially important flatfish species in the North Sea: common sole (*Solea solea*), European plaice (*Pleuronectes platessa*), turbot (*Scophthalmus maximus*), brill (*Scophtalmus rhombus*), European flounder (*Platichthys flesus*), and common dab (*Limanda limanda*). We used a particle-tracking model (Larvae&Co) coupled to a 3D hydrodynamic model to assess the effects of spatial overlap of OWFs with the species’ spawning grounds on the larval fluxes to known nursery grounds. An important overlap between planned areas of OWFs and flatfish spawning grounds was detected, with a resulting proportion of settlers originating from those areas varying from 2% to 16%. Our study suggests that European plaice, common dab, and brill could be the most affected flatfish species, yet with some important local disparities across the North Sea. Consequently, the study represents a first step to quantify the potential impact of OWFs on flatfish settlement, and hence on their population dynamics.
