---
title: "Prediction of the distribution of shrimp species found in southern Benin through the lake Nokoué-Ocean complex"
type: "article"
author: "Sintondji et al."
year: "2022"
publication: "Journal of Aquaculture, Marine Biology & Ecology"
preprint: ""
doi: "https://kosmospublishers.com/prediction-of-the-distribution-of-shrimp-species-found-in-southern-benin-through-the-lake-nokoue-ocean-complex/"
materials: ""
toc: false
categories:
  - shrimp
  - Lake Nokoué, Benin
---

## Citation

> Sintondji S.W., **Gozingan A.S.**, Sohou Z., Taymans M., Baetens K., **Lacroix G.**, Fiogbé E.D. (2022) Prediction of the distribution of shrimp species found in southern Benin through the lake Nokoué-Ocean complex. 2022. Journal of Aquaculture, Marine Biology & Ecology, 116.

## Abstract

The export of shrimps to the European Union was one of the mainstays of the Beninese economy. It is an income-generating activity for the populations living along Lake Nokoué. The lack of a fisheries management strategy has caused a drastic decline in shrimp’s production in Lake Nokoué since 2003. To remedy this problem, it is necessary to hypothesize on their spatial-temporal dynamics in the Lake Nokoué-Cotonou channel complex. This is investigated by combining a literature review on their life cycles and habitat suitability with spatial-temporal evolution of salinity obtained from in-situ observations. The literature review reported four (04) potential families of shrimp species whose part of their life cycle is common to the ecology of Lake Nokoué: Penaeidae (*Penaeus*); Palaemonidae (*Macrobrachium*); Atyidae (*Atya*) and Desmocarididae (*Desmocaris*). The overall results in relation to the life cycle of the shrimp species indicate that adults of the *Macrobrachium*, *Atya* species have a favorable environment in Lake Nokoué from August to November and their larvae must remain in the lake from December to June to ensure their survival. The species of the genus *Desmocaris*, which carry out their entire life cycle in fresh water, can stay in Lake Nokoué from August to November. The species of the genus *Penaeus* have a favorable environment in Lake Nokoué from December to June but their larvae can only survive in the sea. Species of the genus *Caridina* (freshwater) and *Palaemon* (estuary and marine) belonging to the family Palaemonidae can however be found in Lake Nokoué because of their wide distribution on the West African coast although they are not reported in Benin. This research makes it possible to predict the presence or absence of shrimp genera in a lake system, based on their life cycle. Based on the results obtained, we suggest a ban on fishing in Lake Nokoué between December and February and a ban on shrimp fishing in the Cotonou canal for a good management of the shrimp stock in Benin.
