---
title: "Deriving pre-eutrophic conditions from an ensemble model approach for the North-West European Seas"
type: "article"
author: "van Leeuwen et al."
year: "2023"
publication: "Frontiers in Marine Science"
preprint: ""
doi: "https://doi.org/10.3389/fmars.2023.1129951"
materials: ""
toc: false
categories:
  - ensemble modeling
  - COHERENS
  - North-West European Seas
---

## Citation

> van Leeuwen S.M., Lenhart H., Prins T.C., Blauw A., Desmit X., Fernand L., Friedland R., Kerimoglu O., **Lacroix G.**, Van Der Linden A., Lefebvre A., Van Der Molen J., Plus M., Ruvalcaba Baroni I., Silva T., Stegert C., Troost T.A., Vilmin L. (2023) Deriving pre-eutrophic conditions from an ensemble model approach for the North-West European Seas. Frontiers in Marine Science, 10:1129951.

## Abstract

The pre-eutrophic state of marine waters is generally not well known, complicating target setting for management measures to combat eutrophication. We present results from an OSPAR ICG-EMO model assessment to simulate the pre-eutrophic state of North-East Atlantic marine waters. Using an ecosystem model ensemble combined with an observation-based weighting method we derive sophisticated estimates for key eutrophication indicators. Eight modelling centres applied the same riverine nutrient loads, atmospheric nutrient deposition rates and boundary conditions to their specific model set-up to ensure comparability. The pre-eutrophic state was defined as a historic scenario of estimated nutrient inputs (riverine, atmospheric) at around the year 1900, before the invention and widespread use of industrial fertilizers. The period 2009-2014 was used by all participants to simulate both the current state of eutrophication and the pre-eutrophic scenario, to ensure that differences are solely due to the changes in nutrient inputs between the scenarios. Mean values were reported for winter dissolved inorganic nutrients and total nutrients (nitrogen, phosphorus) and the nitrogen to phosphorus ratio, and for growing season chlorophyll, chlorophyll 90th percentile, near-bed oxygen minimum and net phytoplankton production on the level of the OSPAR assessment areas. Results showed distinctly lower nutrient concentrations and nitrogen to phosphorus ratio’s in coastal areas under pre-eutrophic conditions compared to current conditions (except in the Meuse Plume and Seine Plume areas). Chlorophyll concentrations were estimated to be as much as ~40% lower in some areas, as were dissolved inorganic phosphorus levels. Dissolved inorganic nitrogen levels were found to be up to 60% lower in certain assessment areas. The weighted average approach reduced model disparities, and delivered pre-eutrophic concentrations in each assessment area. Our results open the possibility to establish reference values for indicators of eutrophication across marine regions. The use of the new assessment areas ensures local ecosystem functioning is better represented while political boundaries are largely ignored. As such, the reference values are less associated to member states boundaries than to ecosystem boundaries.
